name: Lint OpenAPI

on:
  push:
    branches: [main]
    paths:
      - "openapi.yaml"
      - ".github/workflows/lint-openapi.yml"
  pull_request:
    branches: [main]
    paths:
      - "openapi.yaml"
      - ".github/workflows/lint-openapi.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Lint openapi.yaml
        run: npx @redocly/cli lint ./openapi.yaml --extends recommended-strict
